# Generated by Django 3.1.1 on 2020-09-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestampedmodel',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='등록 일자'),
        ),
    ]
