# Generated by Django 3.1.1 on 2020-10-06 00:19

from django.db import migrations, models
import participants.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='등록 일자')),
                ('file_name', models.CharField(blank=True, max_length=50, verbose_name='파일 이름')),
                ('creator', models.CharField(max_length=50, verbose_name='작성자')),
                ('contents', models.FileField(blank=True, upload_to=participants.models.get_file_path, verbose_name='파일')),
                ('description', models.TextField(verbose_name='파일 설명')),
                ('link', models.TextField(blank=True, verbose_name='링크')),
            ],
            options={
                'verbose_name_plural': '파일',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='등록 일자')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='이름')),
                ('company', models.CharField(max_length=30, null=True, verbose_name='회사')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='이메일')),
                ('dept', models.CharField(max_length=30, null=True, verbose_name='부서')),
                ('phone', models.CharField(max_length=30, null=True, verbose_name='연락처')),
                ('position', models.CharField(max_length=30, null=True, verbose_name='직급')),
            ],
            options={
                'verbose_name_plural': '방문객',
            },
        ),
    ]
