# Generated by Django 3.1.1 on 2020-09-28 01:56

from django.db import migrations, models
import django.db.models.deletion
import participants.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20200924_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel')),
                ('file_name', models.CharField(max_length=50, verbose_name='파일 이름')),
                ('creator', models.CharField(max_length=50, verbose_name='작성자')),
                ('contents', models.FileField(upload_to=participants.models.get_file_path, verbose_name='파일')),
                ('description', models.TextField(verbose_name='파일 설명')),
                ('link', models.TextField(null=True, verbose_name='링크')),
            ],
            options={
                'verbose_name_plural': '파일',
            },
            bases=('core.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='이름')),
                ('company', models.CharField(max_length=30, null=True, verbose_name='회사')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='이메일')),
                ('dept', models.CharField(max_length=30, null=True, verbose_name='부서')),
                ('phone', models.CharField(max_length=30, null=True, verbose_name='연락처')),
                ('position', models.CharField(max_length=30, null=True, verbose_name='직급')),
            ],
            options={
                'verbose_name_plural': '방문객',
            },
            bases=('core.timestampedmodel',),
        ),
    ]
