# Generated by Django 3.1.1 on 2020-09-28 21:05

from django.db import migrations, models
import participants.models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='contents',
            field=models.FileField(null=True, upload_to=participants.models.get_file_path, verbose_name='파일'),
        ),
    ]
